Feat-add-alphabet
FutureBaseEditor/HangmanGame-OYU pull request #2
Opened 2023-05-02 21:34 UTC by Alpay41

Türkçe karakterler olduğu için dizi halinde bu şekilde düzeltme yaptım. Faydalı olur umarım

2023-05-03 18:57 UTC, DilaZerenYilmaz requested changes
Hocam kodlar önceki oluşturduğunuz "feat-add-score"  adlı PR ile aynı görünüyor. Güncelleme yapacak mısınız?

2023-05-03 23:27 UTC, DilaZerenYilmaz requested changes
Hocam harfler dizisini Main içerisinde global olarak tanımlarsak ileride aynı diziyi harf silme metodunda kullanabiliriz. Fonksiyona parametre olarak harf dizisini gönderebiliriz.

2023-05-04 14:11 UTC, FutureBaseEditor commented on Program.cs
> +            for (int harf = 0; harf < harfler.Length - 14; harf++) Console.Write("{0} ", harfler[harf]);
harf < harfler.lenght - 14 yazmak yerine harfler.lenght / 2 yazabiliriz. Daha sağlıklı olur.

2023-05-04 14:13 UTC, FutureBaseEditor commented on Program.cs
> +            for (int harf = 15; harf < harfler.Length; harf++) Console.Write("{0} ", harfler[harf]);
Yukarıdaki satırda belirttiğim gibi int harf =15 yazmak yerine harfler.lenght / 2 yazılabilir.

2023-05-04 14:15 UTC, FutureBaseEditor requested changes
Birkaç satır için yorum yazdım ama genel olarak 2 for yerine tek forlada aynı işlem daha sağlıklı şekilde yapılabilir gibi

2023-05-04 20:39 UTC, Alpay41 commented on Program.cs
> +            for (int harf = 15; harf < harfler.Length; harf++) Console.Write("{0} ", harfler[harf]);
düzeltmeler yapıldı

2023-05-07 23:26 UTC, FutureBaseEditor commented on Program.cs
> +            for (int harf = 15; harf < harfler.Length; harf++) Console.Write("{0} ", harfler[harf]);
int harf =15 yazıyor hala orayıda lenght/2 gibi yapabiliriz

2023-05-08 13:26 UTC, DilaZerenYilmaz commented
Hocam tek bir for'la if(harf == harfler.Length() / 2) Console.WriteLine() kontrolünü yaparak alt satıra geçiş yapabiliriz.

2023-05-08 22:53 UTC, FutureBaseEditor commented
> Hocam tek bir for'la if(harf == harfler.Length() / 2) Console.WriteLine() kontrolünü yaparak alt satıra geçiş yapabiliriz.

Bu yorum göz önünde bulundurulabilir bence. Tek for yeterli olur. if ile

2023-05-11 12:49 UTC, DilaZerenYilmaz submitted a review, later dismissed

2023-05-12 14:15 UTC, DilaZerenYilmaz commented on Program.cs
> +            for (int harf = 15; harf < harfler.Length; harf++) Console.Write("{0} ", harfler[harf]);
@FutureBaseEditor hocam düzeltmeler yapılmış

> int harf =15 yazıyor hala orayıda lenght/2 gibi yapabiliriz

2023-05-13 12:43 UTC, OzanMkyn approved these changes, later dismissed

2023-05-15 16:33 UTC, DilaZerenYilmaz commented
> Birkaç satır için yorum yazdım ama genel olarak 2 for yerine tek forlada aynı işlem daha sağlıklı şekilde yapılabilir gibi

Hocam düzeltme yapılmış, merge için değişiklik talebinizi kapatır mısınız?

2023-05-17 21:15 UTC, FutureBaseEditor submitted a review, later dismissed

2023-05-28 13:07 UTC, Senan545 commented
Alpay Hocam, Alphabet fonksiyonu 2 kez yazilmis, Approve etmeden calismasini denedim error verdi onun icin

2023-06-01 13:09 UTC, Alpay41 commented
@DilaZerenYilmaz @FutureBaseEditor @Senan545 @OzanMkyn ShowAlpabet olarak düzeltildi. harfler global bir değişkene atandı

2023-06-15 00:11 UTC, DilaZerenYilmaz approved these changes

2023-06-15 16:06 UTC, FutureBaseEditor approved these changes

2023-06-15 16:07 UTC, merged